AWSTemplateFormatVersion: '2010-09-09'
Description: HTTP API Gateway proxy para backend em ECS/EKS/ALB
Parameters:
  BackendUrl:
    Type: String
    Description: URL público do backend (ex: http://alb-dns/api)
Resources:
  Api:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: ecommerce-aws-api
      ProtocolType: HTTP

  Integration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref Api
      IntegrationType: HTTP_PROXY
      IntegrationUri: !Ref BackendUrl
      PayloadFormatVersion: '1.0'

  Route:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref Api
      RouteKey: 'ANY /{proxy+}'
      Target: !Sub 'integrations/${Integration}'

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref Api
      StageName: prod
      AutoDeploy: true

Outputs:
  ApiEndpoint:
    Value: !Sub 'https://${Api}.execute-api.${AWS::Region}.amazonaws.com/prod'
