AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway HTTP API skeleton. Optional Cognito authorizer is referenced in comments; fill UserPoolId/ClientId to enable.

Parameters:
  ApiName:
    Type: String
    Default: ecommerce-api

Resources:
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Ref ApiName
      ProtocolType: HTTP

  # Example integration to an ALB (replace with your ALB ARN/URI)
  # Integration:
  #   Type: HTTP_PROXY
  #   IntegrationUri: https://your-alb-dns

Outputs:
  ApiEndpoint:
    Description: API endpoint URL
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
