AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Backup plan skeleton (on-demand backups / vault) for DynamoDB and other resources.

Parameters:
  BackupPlanName:
    Type: String
    Default: ecommerce-backup-plan

Resources:
  BackupVault:
    Type: AWS::Backup::BackupVault
    Properties:
      BackupVaultName: !Ref BackupPlanName

  BackupPlan:
    Type: AWS::Backup::BackupPlan
    Properties:
      BackupPlan:
        BackupPlanName: !Ref BackupPlanName
        Rules:
          - RuleName: daily-dynamodb
            TargetBackupVault: !Ref BackupVault
            ScheduleExpression: cron(0 5 ? * * *)
            StartWindowMinutes: 60
            CompletionWindowMinutes: 180
