AWSTemplateFormatVersion: '2010-09-09'
Description: CloudTrail that records management events and ECR data events into an S3 bucket.

Parameters:
  TrailName:
    Type: String
    Default: ecommerce-aws-cloudtrail
  S3BucketName:
    Type: String
    Default: !Sub "ecommerce-aws-cloudtrail-logs-${AWS::AccountId}-${AWS::Region}"

Resources:
  CloudTrailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      VersioningConfiguration:
        Status: Enabled

  CloudTrailLogPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CloudTrailBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudTrailPutObject
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "arn:aws:s3:::${S3BucketName}/AWSLogs/${AWS::AccountId}/*"

  CloudTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: !Ref TrailName
      S3BucketName: !Ref CloudTrailBucket
      IsMultiRegionTrail: true
      IncludeGlobalServiceEvents: true
      EnableLogFileValidation: true
      IsLogging: true
      EventSelectors:
        - ReadWriteType: All
          IncludeManagementEvents: true
        - ReadWriteType: All
          IncludeManagementEvents: false
          DataResources:
            - Type: AWS::ECR::Repository
              Values:
                - !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/*"

Outputs:
  CloudTrailBucketName:
    Description: S3 bucket used by CloudTrail
    Value: !Ref CloudTrailBucket
