AWSTemplateFormatVersion: '2010-09-09'
Description: Enable CloudTrail for ECR events and S3 log bucket
Parameters:
  TrailName:
    Type: String
    Default: ecommerce-aws-trail
  LogBucketName:
    Type: String
    Default: ecommerce-aws-cloudtrail-logs
Resources:
  TrailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref LogBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  Trail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: !Ref TrailName
      S3BucketName: !Ref LogBucketName
      IsLogging: true
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true
      EventSelectors:
        - ReadWriteType: All
          IncludeManagementEvents: true
Outputs:
  TrailArn:
    Value: !Ref Trail
