AWSTemplateFormatVersion: '2010-09-09'
Description: Create ECR repositories (immutable + lifecycle) using the fixed names used by CI/CD.

Parameters:
  BackendRepositoryName:
    Type: String
    Default: ecommerce-ecr-backend
    Description: Name of the backend ECR repository (keep default to match CI/CD)
  FrontendRepositoryName:
    Type: String
    Default: ecommerce-ecr-frontend
    Description: Name of the frontend ECR repository (keep default to match CI/CD)

Resources:
  ECRRepositoryBackend:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref BackendRepositoryName
      ImageTagMutability: IMMUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire images older than last 30 by count",
                "selection": { "tagStatus": "any", "countType": "imageCountMoreThan", "countNumber": 30 },
                "action": { "type": "expire" }
              }
            ]
          }

  ECRRepositoryFrontend:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref FrontendRepositoryName
      ImageTagMutability: IMMUTABLE
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire images older than last 30 by count",
                "selection": { "tagStatus": "any", "countType": "imageCountMoreThan", "countNumber": 30 },
                "action": { "type": "expire" }
              }
            ]
          }

Outputs:
  BackendRepositoryUri:
    Description: URI of the backend ECR repository
    Value: !GetAtt ECRRepositoryBackend.RepositoryUri
  FrontendRepositoryUri:
    Description: URI of the frontend ECR repository
    Value: !GetAtt ECRRepositoryFrontend.RepositoryUri
