AWSTemplateFormatVersion: '2010-09-09'
Description: SNS topic and sample CloudWatch alarm resources to notify scale events.

Parameters:
  TopicName:
    Type: String
    Default: ecommerce-scale-notifications
  NotificationEmail:
    Type: String
    Default: jonathanbimbati@gmail.com
    Description: (Opcional) E-mail para assinar o tópico SNS. Deixe vazio para não criar assinatura.

Conditions:
  UseEmailSubscription: !Not [ !Equals [ !Ref NotificationEmail, '' ] ]

Resources:
  ScaleTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref TopicName

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Condition: UseEmailSubscription
    Properties:
      Protocol: email
      Endpoint: !Ref NotificationEmail
      TopicArn: !Ref ScaleTopic

Outputs:
  ScaleTopicArn:
    Value: !Ref ScaleTopic
    Description: SNS topic ARN for scaling notifications
