AWSTemplateFormatVersion: '2010-09-09'
Description: SNS topic and sample CloudWatch alarm resources to notify scale events.

Parameters:
  TopicName:
    Type: String
    Default: ecommerce-scale-notifications

Resources:
  ScaleTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref TopicName

  ScaleTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref ScaleTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement: []

Outputs:
  ScaleTopicArn:
    Value: !Ref ScaleTopic
    Description: SNS topic ARN for scaling notifications
