AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template - DynamoDB table + Lambda (stream trigger + http endpoint)

Parameters:
  JwtSecretParam:
    Type: String
    Description: "JWT secret value (use SSM SecureString name or pass the raw secret)."

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    Environment:
      Variables:
        TABLE_NAME: !Ref ProductsTable
        DYNAMODB_TABLE: !Ref ProductsTable

Resources:
  UploadsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-uploads'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedMethods: [ 'PUT', 'POST', 'GET', 'HEAD' ]
            AllowedOrigins: [ '*' ]
            AllowedHeaders: [ '*' ]
            MaxAge: 3000

  UploadsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UploadsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadForPublicPrefix
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub '${UploadsBucket.Arn}/public/*'


  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-Products'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-Users'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ProductsProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-ProductsProcessor'
      Handler: streamHandler.handler
      CodeUri: backend/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
        - Statement:
            - Effect: Allow
              Action: sns:Publish
              Resource: !Ref NotificationTopic
      Environment:
        Variables:
          NOTIFICATION_TOPIC_ARN: !Ref NotificationTopic
          USERS_TABLE: !Ref UsersTable
          JWT_SECRET: !Ref JwtSecretParam
      Events:
        ProductsStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt ProductsTable.StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
        ProductsApi:
          Type: Api
          Properties:
            Path: /Product
            Method: post

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-Api'
      Handler: lambda/apiHandler.handler
      CodeUri: backend/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - Statement:
            - Effect: Allow
              Action: sns:Publish
              Resource: !Ref NotificationTopic
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:PutObjectAcl
              Resource: !Sub '${UploadsBucket.Arn}/*'
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
          JWT_SECRET: !Ref JwtSecretParam
          S3_BUCKET: !Ref UploadsBucket
          S3_PREFIX: 'public/'
          S3_PUBLIC_URL_BASE: !Sub 'https://${UploadsBucket}.s3.${AWS::Region}.amazonaws.com'
      Events:
        ProxyApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${AWS::StackName}-ProductNotifications'

  NotificationSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: jonathanbimbati@gmail.com
      TopicArn: !Ref NotificationTopic

  NotificationConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-NotificationConsumer'
      Handler: lambda/notificationHandler.handler
      CodeUri: backend/
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'

  NotificationLambdaSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: lambda
      Endpoint: !GetAtt NotificationConsumerFunction.Arn
      TopicArn: !Ref NotificationTopic

  NotificationLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt NotificationConsumerFunction.Arn
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref NotificationTopic


Outputs:
  ProductsTableName:
    Description: "DynamoDB table name"
    Value: !Ref ProductsTable

  ProductsProcessorFunctionArn:
    Description: "Lambda function ARN"
    Value: !GetAtt ProductsProcessorFunction.Arn

  ProductsApiEndpoint:
    Description: "API endpoint for manual invocation (POST /Product)"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/Product"

  ApiBaseEndpoint:
    Description: "API base endpoint (use /Prod/api/... for auth/product routes)"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  UploadsBucketName:
    Description: "Uploads S3 bucket name"
    Value: !Ref UploadsBucket

  NotificationTopicArn:
    Description: "SNS topic ARN for product notifications"
    Value: !Ref NotificationTopic
