apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: ecommerce-backend
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: ecommerce-backend
  type: ClusterIP
