apiVersion: v1
kind: Service
metadata:
  name: ecommerce-backend
  labels:
    app: ecommerce-backend
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: ecommerce-backend
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-backend
  labels:
    app: ecommerce-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-backend
  template:
    metadata:
      labels:
        app: ecommerce-backend
    spec:
      serviceAccountName: ecommerce-backend-sa
      containers:
        - name: backend
          image: 199299155478.dkr.ecr.us-east-1.amazonaws.com/ecommerce-aws-backend@sha256:102006a410303c09a76881c067140551bdac60afe8e07dc149ad06fda597806e
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: AWS_REGION
              value: us-east-1
            - name: DYNAMODB_TABLE
              value: "ecommerce-aws-Products"
            - name: AWS_WEB_IDENTITY_TOKEN_FILE
              value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
            - name: AWS_ROLE_ARN
              value: arn:aws:iam::199299155478:role/eksctl-ecommerce-eks-addon-iamserviceaccount--Role1-Lp7MzZ9QjPHU
          readinessProbe:
            httpGet:
              path: /api/products
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
      automountServiceAccountToken: false
      volumes:
        - name: aws-iam-token
          projected:
            sources:
              - serviceAccountToken:
                  path: token
                  audience: sts.amazonaws.com
                  expirationSeconds: 3600
      # mount projected token into the container
      # (the container will find it at the path set in AWS_WEB_IDENTITY_TOKEN_FILE)
      # mount handled by Kubernetes automatically into /var/run/secrets/eks.amazonaws.com/serviceaccount