apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend-nodeport
  namespace: staging
  labels:
    app: ecommerce-frontend
spec:
  type: NodePort
  selector:
    app: ecommerce-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080
