apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - service-account.yaml
  - secret-jwt.yaml
  - frontend-hpa.yaml

images:
  - name: ecommerce-ecr-backend
    newName: 199299155478.dkr.ecr.us-east-1.amazonaws.com/ecommerce-ecr-backend
    newTag: "@sha256:102006a410303c09a76881c067140551bdac60afe8e07dc149ad06fda597806e"
  - name: ecommerce-ecr-frontend
    newName: 199299155478.dkr.ecr.us-east-1.amazonaws.com/ecommerce-ecr-frontend
    newTag: "@sha256:0b9177c17d170a4968a57b910ea7247ee6339d1ab451d312055bf346f569a450"
