apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  # base64 encoded secret. Replace with your secret or create from kubectl:
  # kubectl create secret generic jwt-secret --from-literal=JWT_SECRET=supersecret
  JWT_SECRET: "c3VwZXJzZWNyZXQ="
