name: Deploy Infra (manual)

on:
  workflow_dispatch:
    inputs:
      CognitoEnabled:
        description: 'Enable Cognito? true|false'
        required: false
        default: 'false'

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Validate CF template
        run: |
          aws cloudformation validate-template --template-body file://infra/cloudformation/apigw-http.yaml

      - name: Deploy API Gateway stack
        run: |
          aws cloudformation deploy --template-file infra/cloudformation/apigw-http.yaml --stack-name ecommerce-apigw --capabilities CAPABILITY_NAMED_IAM --parameter-overrides CognitoEnabled=${{ github.event.inputs.CognitoEnabled }}
